### PR TITLE
Add Typescript, use Jest, use linting rules, use up to date packages and use react-intl

### PR DESCRIPTION
**Pull request by floric**
* all common and up to date packages for a better and easier start

### CODE REVIEW

**Comment by floric** [comment]
@oakstair FYI

**Comment by wyaeld** [comment]
Not the maintainer, but some feedback

1. hugely useful to have the libraries updated
2. Jest and react-intl align more nicely with community direction
3.  "Successfull" is spelt "Successful".

however

4. Switching the entire frontend project over to Typescript without discussion though is the sort of thing usually frowned on.  Consumers of a project don't always have the capacity or capability to make the change.  React itself isn't Typescript, so that's a choice that doesn't align with the core community.

**Comment by floric** [comment]
Yeah, I was in rush and needed it personally. Later, after the PR, I also thought about point 4. and I would totally understand the decision not to merge it some day.
Personally, I think, Typescript is quite easy to learn and makes complex Webapps so much more easy to develop, understand and debug, also for beginners. I also didn't reintegrate the Redux Devtools again. If you like, feel free to continue the work and get rid of Typescript. It should be enough to remove all types and remove the Typescript loader in Webpack again.

**Comment by geowarin** [comment]
Hello @floric, I just wanted to say that I have seen your PR and I'm really grateful you took the time to submit it :1st_place_medal: 

I really like the version bump and I think maybe the move to react-intl is the good one.

I'm a big proponent of typecsript and I wouldn't use react without it but maybe it belongs to a fork.
I'm not sure pushing yet another technology to the stack will satisfy everyone here.

It is very difficult for me to review this PR as it is. It does too much.
If you're still motivated I would gladly review and merge seperate PRs for:

1. Bump of the dependencies
2. React-intl
3. jest

**Comment by floric** [comment]
Hey @geowarin,
I can totally understand this. I'm not sure, when I can do this, but I will have a look. Your base project helped me a lot for mine, so giving something back is the least I can do. :)
Personally, I still think always using Typescript would make JS development even for starters so much easier and more predictable (as long as the libraries and type defs are synchronized and up to date)

**Pull request closed without merging**
