### PR TITLE
Upgraded to latest and greatest versions

### PR DESCRIPTION
**Pull request by oakstair**
This pull request includes the fix for the YarnStart location plus upgrades the project to the latest version of webpack and other modules.

I also however get an empty page when I visit localhost:3000 so please add an image of the expected starting screen plus help out on what could be the problem.

I am new to React/Reduct/Webpack and more or less everything that has happened on the frontend side the last 5 years. Cooool stuff however man!

### CODE REVIEW

**Comment by floric** [comment]
Hey :) I just saw this project and wanted to do something similar locally: upgrading all backend and frontend packages. :+1: But this PR saves some work.
The only thing left would be adding TypeScript. If it makes sense I could give it a try :) Anyway, I hope this gets merged.

**Comment by floric** [comment]
I just tried your changes:
Your path change to "../frontend" for the Yarn runner didn't work for me, the old one was correct.
The white page shouldn't be a white page. In the current master state, a sample application will be shown. This is not the case for your changes as some upgrades or other changes broke the frontend. I'll have a look if I can fix them.

**Comment by oakstair** [comment]
I may have step into deep water since I am new to React/Redux and they made breaking changes between 2/3 to React4. This PR is currently not working. I will make a new try to get it up working during the weekend. I wanted to base my React/Redux learning project on this project since I really liked the setup.

**Comment by floric** [comment]
I ported the frontend to Typescript 2.3 and upgraded all possible deps. The only other change was, that I changed from "counterpart" for i18n to "react-intl(-redux)".
But general after a few months of Frontend I've learned that "Never change a running system" is even truer in frontend works so I try to stick to the current dependencies after this PR. :smile: 
I'll post a PR maybe in a few days, when I'm sure all is fine. :)

**Pull request closed without merging**
